# Generated by Django 5.2.3 on 2025-06-13 22:11

import common.pk_generator
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.pk_generator.generate_id,
                        editable=False,
                        max_length=37,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("accepting_work", models.BooleanField(default=True)),
                (
                    "user_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
