# Generated by Django 5.2.3 on 2025-06-21 23:41

import common.pk_generator
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.pk_generator.generate_id,
                        editable=False,
                        max_length=37,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "accepting_work",
                    models.BooleanField(default=True, verbose_name="Open To Work"),
                ),
                (
                    "applicant_bio",
                    models.TextField(max_length=3000, verbose_name="Cover Letter"),
                ),
                (
                    "banner_img",
                    models.URLField(blank=True, null=True, verbose_name="Banner Image"),
                ),
                (
                    "applicant_photo",
                    models.URLField(blank=True, null=True, verbose_name="Photo"),
                ),
                (
                    "current_title",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Current Title",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicantContactMethods",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.pk_generator.generate_id,
                        editable=False,
                        max_length=37,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("whatsapp", "WhatsApp"),
                            ("signal", "Signal"),
                        ],
                        max_length=20,
                        verbose_name="Contact Type",
                    ),
                ),
                ("value", models.CharField(max_length=75)),
                (
                    "show",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Checked will display on resume web page.",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contact Information",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ApplicantSocials",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.pk_generator.generate_id,
                        editable=False,
                        max_length=37,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("github", "GitHub"),
                            ("twitter", "Twitter"),
                            ("portfolio", "Portfolio"),
                            ("mastodon", "Mastodon"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "show",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Checked will display on resume web page.",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Socials",
                "ordering": ["order"],
            },
        ),
    ]
