# Generated by Django 5.2.3 on 2025-06-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="applicant_bio",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
    ]
