# Generated by Django 5.2.3 on 2025-06-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0002_applicant_applicant_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="applicant_bio",
            field=models.TextField(max_length=300),
        ),
    ]
