# Generated by Django 5.2.3 on 2025-06-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="allow_feedback",
            field=models.BooleanField(default=True),
        ),
    ]
