# Generated by Django 5.2.3 on 2025-06-14 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0003_alter_applicant_applicant_bio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="accepting_work",
            field=models.BooleanField(default=True, verbose_name="Open To Work"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="applicant_bio",
            field=models.TextField(max_length=300, verbose_name="Biography"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="user_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
