# Generated by Django 5.2.3 on 2025-06-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0004_alter_applicant_accepting_work_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="banner_img",
            field=models.URLField(blank=True, null=True),
        ),
    ]
