# Generated by Django 5.2.3 on 2025-06-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0005_applicant_banner_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="applicant_photo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
