# Generated by Django 5.2.3 on 2025-06-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0006_applicant_applicant_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="applicant_bio",
            field=models.TextField(max_length=3000, verbose_name="Biography"),
        ),
    ]
