# Generated by Django 5.2.3 on 2025-06-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0007_alter_applicant_applicant_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="current_title",
            field=models.CharField(default="Software Developer", max_length=50),
            preserve_default=False,
        ),
    ]
