# Generated by Django 5.2.3 on 2025-06-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0008_applicant_current_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="applicant_photo",
            field=models.URLField(blank=True, null=True, verbose_name="Photo"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="banner_img",
            field=models.URLField(blank=True, null=True, verbose_name="Banner Image"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="current_title",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Current Title"
            ),
        ),
    ]
