# Generated by Django 5.2.3 on 2025-06-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0009_alter_applicant_applicant_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="linkd_in_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicant",
            name="show_contact_info",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="applicant",
            name="show_socials",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="applicant",
            name="source_control_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
