# Generated by Django 5.2.3 on 2025-06-20 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applicant",
            "0010_applicant_linkd_in_url_applicant_show_contact_info_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicantContactMethods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("whatsapp", "WhatsApp"),
                            ("signal", "Signal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("show", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "applicant_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_links",
                        to="applicant.applicant",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("applicant_reltn", "contact_type")},
            },
        ),
        migrations.CreateModel(
            name="ApplicantSocials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("github", "GitHub"),
                            ("twitter", "Twitter"),
                            ("portfolio", "Portfolio"),
                            ("mastodon", "Mastodon"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("show", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "applicant_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="applicant.applicant",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("applicant_reltn", "platform")},
            },
        ),
    ]
