# Generated by Django 5.2.3 on 2025-06-20 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0011_applicantcontactmethods_applicantsocials"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicantcontactmethods",
            options={
                "ordering": ["order"],
                "verbose_name_plural": "Contact Information",
            },
        ),
        migrations.AlterModelOptions(
            name="applicantsocials",
            options={"ordering": ["order"], "verbose_name_plural": "Socials"},
        ),
        migrations.AlterField(
            model_name="applicantcontactmethods",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_links",
                to="applicant.applicant",
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="applicantcontactmethods",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("whatsapp", "WhatsApp"),
                    ("signal", "Signal"),
                ],
                max_length=20,
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="applicantcontactmethods",
            name="order",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="applicantcontactmethods",
            name="show",
            field=models.BooleanField(
                default=True, help_text="Checked will display on resume web page."
            ),
        ),
        migrations.AlterField(
            model_name="applicantcontactmethods",
            name="value",
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name="applicantsocials",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_links",
                to="applicant.applicant",
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="applicantsocials",
            name="order",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="applicantsocials",
            name="show",
            field=models.BooleanField(
                default=True, help_text="Checked will display on resume web page."
            ),
        ),
    ]
