# Generated by Django 5.2.3 on 2025-06-20 01:16

import common.pk_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0012_alter_applicantcontactmethods_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicantcontactmethods",
            name="id",
            field=models.CharField(
                default=common.pk_generator.generate_id,
                editable=False,
                max_length=37,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="applicantsocials",
            name="id",
            field=models.CharField(
                default=common.pk_generator.generate_id,
                editable=False,
                max_length=37,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
