# Generated by Django 5.2.3 on 2025-06-20 01:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0013_alter_applicantcontactmethods_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicantsocials",
            name="order",
            field=models.IntegerField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
    ]
