# Generated by Django 5.2.3 on 2025-06-20 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0014_alter_applicantsocials_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicantcontactmethods",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("whatsapp", "WhatsApp"),
                    ("signal", "Signal"),
                ],
                max_length=20,
                verbose_name="Contact Type",
            ),
        ),
        migrations.AlterField(
            model_name="applicantcontactmethods",
            name="order",
            field=models.IntegerField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="applicantcontactmethods",
            name="show",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Checked will display on resume web page.",
            ),
        ),
        migrations.AlterField(
            model_name="applicantsocials",
            name="show",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Checked will display on resume web page.",
            ),
        ),
    ]
