# Generated by Django 5.2.3 on 2025-06-20 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0015_alter_applicantcontactmethods_contact_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicant",
            name="linkd_in_url",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="show_contact_info",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="show_socials",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="source_control_url",
        ),
        migrations.AlterField(
            model_name="applicant",
            name="applicant_bio",
            field=models.TextField(max_length=3000, verbose_name="Cover Letter"),
        ),
        migrations.AlterField(
            model_name="applicantcontactmethods",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_method",
                to="applicant.applicant",
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="applicantsocials",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social",
                to="applicant.applicant",
                verbose_name="Applicant",
            ),
        ),
    ]
