# Generated by Django 5.2.3 on 2025-06-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="monthly_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
