# Generated by Django 5.2.3 on 2025-06-21 23:41

import common.pk_generator
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applicant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.pk_generator.generate_id,
                        editable=False,
                        max_length=37,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=75, verbose_name="Project Name")),
                (
                    "demo_url",
                    models.URLField(blank=True, null=True, verbose_name="Demo"),
                ),
                (
                    "source_control_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Source Control"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, null=True, verbose_name="Video"),
                ),
                (
                    "description",
                    models.TextField(max_length=1000, verbose_name="Description"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "applicant_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="applicant.applicant",
                        verbose_name="Applicant",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDetails",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.pk_generator.generate_id,
                        editable=False,
                        max_length=37,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "detail_text",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "detail_image",
                    models.URLField(blank=True, null=True, verbose_name="Image"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "project_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_details",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project Details",
                "ordering": ["order"],
            },
        ),
    ]
