# Generated by Django 5.2.3 on 2025-06-14 01:03

import common.pk_generator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applicant", "0005_applicant_banner_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.pk_generator.generate_id,
                        editable=False,
                        max_length=37,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=75)),
                ("demo_url", models.URLField(blank=True, null=True)),
                ("source_control_url", models.URLField(blank=True, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "applicant_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applicant.applicant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectDetails",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.pk_generator.generate_id,
                        editable=False,
                        max_length=37,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "detail_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("detail_image", models.URLField(blank=True, null=True)),
                (
                    "project_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
