# Generated by Django 5.2.3 on 2025-06-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="projectdetails",
            name="order",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
