# Generated by Django 5.2.3 on 2025-06-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_order_projectdetails_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
