# Generated by Django 5.2.3 on 2025-06-18 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectdetails",
            name="project_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_details",
                to="projects.project",
            ),
        ),
    ]
