# Generated by Django 5.2.3 on 2025-06-19 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0009_alter_applicant_applicant_photo_and_more"),
        ("projects", "0004_alter_projectdetails_project_reltn"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectdetails",
            options={"verbose_name_plural": "Project Details"},
        ),
        migrations.AlterField(
            model_name="project",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="applicant.applicant",
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="demo_url",
            field=models.URLField(blank=True, null=True, verbose_name="Demo"),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                default="test", max_length=500, verbose_name="Description"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=75, verbose_name="Project Name"),
        ),
        migrations.AlterField(
            model_name="project",
            name="source_control_url",
            field=models.URLField(blank=True, null=True, verbose_name="Source Control"),
        ),
        migrations.AlterField(
            model_name="project",
            name="video_url",
            field=models.URLField(blank=True, null=True, verbose_name="Video"),
        ),
        migrations.AlterField(
            model_name="projectdetails",
            name="detail_image",
            field=models.URLField(blank=True, null=True, verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="projectdetails",
            name="detail_text",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Short Description"
            ),
        ),
        migrations.AlterField(
            model_name="projectdetails",
            name="project_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_details",
                to="projects.project",
                verbose_name="Project",
            ),
        ),
    ]
