# Generated by Django 5.2.3 on 2025-06-19 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applicant",
            "0010_applicant_linkd_in_url_applicant_show_contact_info_and_more",
        ),
        ("projects", "0005_alter_projectdetails_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="applicant.applicant",
                verbose_name="Applicant",
            ),
        ),
    ]
