# Generated by Django 5.2.3 on 2025-06-20 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_project_applicant_reltn"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="projectdetails",
            options={"ordering": ["order"], "verbose_name_plural": "Project Details"},
        ),
    ]
