# Generated by Django 5.2.3 on 2025-06-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_project_order_alter_projectdetails_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="Description"),
        ),
    ]
