# Generated by Django 5.2.3 on 2025-06-21 23:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applicant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicantFeedBack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=2000, null=True, verbose_name="Comment"
                    ),
                ),
                ("full_name", models.CharField(max_length=75, verbose_name="Name")),
                ("phone_number", models.CharField(max_length=11, verbose_name="Phone")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=125, null=True, verbose_name="Company"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP")),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "applicant_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applicant.applicant",
                        verbose_name="Applicant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Feedback",
            },
        ),
    ]
