# Generated by Django 5.2.3 on 2025-06-17 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantfeedback",
            name="company",
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name="applicantfeedback",
            name="email",
            field=models.EmailField(default="test", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicantfeedback",
            name="full_name",
            field=models.CharField(default="test", max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicantfeedback",
            name="phone_number",
            field=models.CharField(default="test", max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicantfeedback",
            name="rating",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
    ]
