# Generated by Django 5.2.3 on 2025-06-27 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0003_applicant_allow_feedback"),
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(max_length=1000, verbose_name="Question"),
                ),
                (
                    "question_answer",
                    models.TextField(max_length=3000, verbose_name="Answer"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "applicant_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applicant.applicant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Question Answers",
                "ordering": ["-created_at"],
            },
        ),
    ]
