# Generated by Django 5.2.3 on 2025-06-18 23:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0009_alter_applicant_applicant_photo_and_more"),
        ("feedback", "0002_applicantfeedback_company_applicantfeedback_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicantfeedback",
            options={"verbose_name_plural": "Feedback"},
        ),
        migrations.AlterField(
            model_name="applicantfeedback",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="applicant.applicant",
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="applicantfeedback",
            name="comment",
            field=models.TextField(
                blank=True, max_length=2000, null=True, verbose_name="Comment"
            ),
        ),
        migrations.AlterField(
            model_name="applicantfeedback",
            name="company",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="Company"
            ),
        ),
        migrations.AlterField(
            model_name="applicantfeedback",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="applicantfeedback",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="applicantfeedback",
            name="full_name",
            field=models.CharField(max_length=75, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="applicantfeedback",
            name="ip_address",
            field=models.GenericIPAddressField(verbose_name="IP"),
        ),
        migrations.AlterField(
            model_name="applicantfeedback",
            name="phone_number",
            field=models.CharField(max_length=11, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="applicantfeedback",
            name="rating",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Rating",
            ),
        ),
        migrations.AlterField(
            model_name="applicantfeedback",
            name="user_agent",
            field=models.TextField(blank=True, null=True, verbose_name="User Agent"),
        ),
    ]
