# Generated by Django 5.2.3 on 2025-06-18 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_alter_applicantfeedback_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicantfeedback",
            name="rating",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Rating",
            ),
        ),
    ]
