# Generated by Django 5.2.3 on 2025-06-21 23:41

import common.pk_generator
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applicant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalContext",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.pk_generator.generate_id,
                        editable=False,
                        max_length=37,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "context_text",
                    models.CharField(
                        help_text="Additional Information you want to tell a LLM to know you more.",
                        max_length=255,
                        verbose_name="Context",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "applicant_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context",
                        to="applicant.applicant",
                        verbose_name="Applicant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "LLM Context",
            },
        ),
        migrations.CreateModel(
            name="Awards",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.pk_generator.generate_id,
                        editable=False,
                        max_length=37,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reward_name",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Award Name"
                    ),
                ),
                (
                    "reward_descrption",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "applicant_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="applicant.applicant",
                        verbose_name="Applicant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Awards",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.pk_generator.generate_id,
                        editable=False,
                        max_length=37,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Certification Name"
                    ),
                ),
                ("attained_on", models.DateField(verbose_name="Recieved Date")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "applicant_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="applicant.applicant",
                        verbose_name="Applicant",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.pk_generator.generate_id,
                        editable=False,
                        max_length=37,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("none", "No Formal Education"),
                            ("primary", "Primary School"),
                            ("middle", "Middle School"),
                            ("high_school", "High School Diploma or GED"),
                            ("associate", "Associate Degree"),
                            ("vocational", "Vocational/Technical Certificate"),
                            ("bachelor", "Bachelor's Degree"),
                            ("post_bachelor", "Post-Bachelor Certificate"),
                            ("master", "Master's Degree"),
                            ("post_master", "Post-Master Certificate"),
                            ("doctoral", "Doctoral Degree"),
                            ("professional", "Professional Degree (MD, JD, etc.)"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Education Level",
                    ),
                ),
                (
                    "area_of_study",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Major",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Institution")),
                ("from_date", models.DateField(verbose_name="Start Date")),
                ("to_date", models.DateField(verbose_name="End Date")),
                (
                    "currently_attending",
                    models.BooleanField(default=False, verbose_name="Attending"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "applicant_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="applicant.applicant",
                        verbose_name="Applicant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Education",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="References",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.pk_generator.generate_id,
                        editable=False,
                        max_length=37,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="Reference Full Name",
                    ),
                ),
                ("relation", models.CharField(max_length=255, verbose_name="Relation")),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Job Title"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "reference_recommendation",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Recommendation",
                    ),
                ),
                (
                    "applicant_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="applicant.applicant",
                        verbose_name="Applicant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "References",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.pk_generator.generate_id,
                        editable=False,
                        max_length=37,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "skill_name",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Skill"
                    ),
                ),
                (
                    "skill_description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Years of Experience"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "skill_logo",
                    models.URLField(blank=True, null=True, verbose_name="Logo"),
                ),
                (
                    "applicant_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="applicant.applicant",
                        verbose_name="Applicant",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
