# Generated by Django 5.2.3 on 2025-06-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant_details", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="to_date",
            field=models.DateField(blank=True, null=True, verbose_name="End Date"),
        ),
    ]
