# Generated by Django 5.2.3 on 2025-06-13 23:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant_details", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="currently_attending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="education",
            name="from_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="education",
            name="to_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
