# Generated by Django 5.2.3 on 2025-06-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applicant_details",
            "0002_education_currently_attending_education_from_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="area_of_study",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
