# Generated by Django 5.2.3 on 2025-06-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant_details", "0002_alter_education_to_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalcontext",
            name="context_text",
            field=models.TextField(
                help_text="Additional Information you want to tell a LLM to know you more.",
                max_length=300,
                verbose_name="Context",
            ),
        ),
    ]
