# Generated by Django 5.2.3 on 2025-06-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant_details", "0003_education_area_of_study"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="skill_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
