# Generated by Django 5.2.3 on 2025-06-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant_details", "0004_alter_skill_skill_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="years_of_experience",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
