# Generated by Django 5.2.3 on 2025-06-13 23:47

import common.pk_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant_details", "0005_skill_years_of_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalcontext",
            name="id",
            field=models.CharField(
                default=common.pk_generator.generate_id,
                editable=False,
                max_length=37,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="bio",
            name="id",
            field=models.CharField(
                default=common.pk_generator.generate_id,
                editable=False,
                max_length=37,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="certification",
            name="id",
            field=models.CharField(
                default=common.pk_generator.generate_id,
                editable=False,
                max_length=37,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="id",
            field=models.CharField(
                default=common.pk_generator.generate_id,
                editable=False,
                max_length=37,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="references",
            name="id",
            field=models.CharField(
                default=common.pk_generator.generate_id,
                editable=False,
                max_length=37,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="id",
            field=models.CharField(
                default=common.pk_generator.generate_id,
                editable=False,
                max_length=37,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
