# Generated by Django 5.2.3 on 2025-06-14 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applicant_details", "0006_alter_additionalcontext_id_alter_bio_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bio",
        ),
    ]
