# Generated by Django 5.2.3 on 2025-06-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant_details", "0007_delete_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalcontext",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="order",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="education",
            name="order",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="references",
            name="job_title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="references",
            name="order",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="skill",
            name="order",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
