# Generated by Django 5.2.3 on 2025-06-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applicant_details",
            "0008_additionalcontext_active_certification_order_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="skill_logo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
