# Generated by Django 5.2.3 on 2025-06-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant_details", "0009_skill_skill_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="references",
            name="reference_recommendation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
