# Generated by Django 5.2.3 on 2025-06-17 23:16

import common.pk_generator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0008_applicant_current_title"),
        ("applicant_details", "0010_references_reference_recommendation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Awards",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.pk_generator.generate_id,
                        editable=False,
                        max_length=37,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reward_name", models.CharField(max_length=50)),
                (
                    "reward_descrption",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("order", models.PositiveIntegerField(default=100)),
                (
                    "applicant_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applicant.applicant",
                    ),
                ),
            ],
        ),
    ]
