# Generated by Django 5.2.3 on 2025-06-18 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0009_alter_applicant_applicant_photo_and_more"),
        ("applicant_details", "0011_awards"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additionalcontext",
            options={"verbose_name_plural": "LLM Context"},
        ),
        migrations.AlterModelOptions(
            name="awards",
            options={"verbose_name_plural": "Awards"},
        ),
        migrations.AlterModelOptions(
            name="education",
            options={"verbose_name_plural": "Education"},
        ),
        migrations.AlterModelOptions(
            name="references",
            options={"verbose_name_plural": "References"},
        ),
        migrations.AlterField(
            model_name="additionalcontext",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="applicant.applicant",
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="additionalcontext",
            name="context_text",
            field=models.CharField(
                help_text="Additional Information you want to tell a LLM to know you more.",
                max_length=255,
                verbose_name="Context",
            ),
        ),
        migrations.AlterField(
            model_name="awards",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="applicant.applicant",
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="awards",
            name="reward_descrption",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Short Description"
            ),
        ),
        migrations.AlterField(
            model_name="awards",
            name="reward_name",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="Award Name"
            ),
        ),
        migrations.AlterField(
            model_name="certification",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="applicant.applicant",
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="certification",
            name="attained_on",
            field=models.DateField(verbose_name="Recieved Date"),
        ),
        migrations.AlterField(
            model_name="certification",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Certification Name"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="applicant.applicant",
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="area_of_study",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="Major",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="currently_attending",
            field=models.BooleanField(default=False, verbose_name="Attending"),
        ),
        migrations.AlterField(
            model_name="education",
            name="education_level",
            field=models.CharField(
                choices=[
                    ("none", "No Formal Education"),
                    ("primary", "Primary School"),
                    ("middle", "Middle School"),
                    ("high_school", "High School Diploma or GED"),
                    ("associate", "Associate Degree"),
                    ("vocational", "Vocational/Technical Certificate"),
                    ("bachelor", "Bachelor's Degree"),
                    ("post_bachelor", "Post-Bachelor Certificate"),
                    ("master", "Master's Degree"),
                    ("post_master", "Post-Master Certificate"),
                    ("doctoral", "Doctoral Degree"),
                    ("professional", "Professional Degree (MD, JD, etc.)"),
                    ("other", "Other"),
                ],
                max_length=255,
                verbose_name="Education Level",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="from_date",
            field=models.DateField(verbose_name="Start Date"),
        ),
        migrations.AlterField(
            model_name="education",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Institution"),
        ),
        migrations.AlterField(
            model_name="education",
            name="to_date",
            field=models.DateField(verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="references",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="applicant.applicant",
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="references",
            name="job_title",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Job Title"
            ),
        ),
        migrations.AlterField(
            model_name="references",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Reference Full Name"
            ),
        ),
        migrations.AlterField(
            model_name="references",
            name="reference_recommendation",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Recommendation"
            ),
        ),
        migrations.AlterField(
            model_name="references",
            name="relation",
            field=models.CharField(max_length=255, verbose_name="Relation"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="applicant.applicant",
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="skill_description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Short Description"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="skill_logo",
            field=models.URLField(blank=True, null=True, verbose_name="Logo"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="skill_name",
            field=models.CharField(db_index=True, max_length=50, verbose_name="Skill"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="years_of_experience",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Years of Experience"
            ),
        ),
    ]
