# Generated by Django 5.2.3 on 2025-06-19 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0009_alter_applicant_applicant_photo_and_more"),
        (
            "applicant_details",
            "0012_alter_additionalcontext_options_alter_awards_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalcontext",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="context",
                to="applicant.applicant",
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="awards",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="awards",
                to="applicant.applicant",
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="certification",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certifications",
                to="applicant.applicant",
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education",
                to="applicant.applicant",
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="education_level",
            field=models.CharField(
                choices=[
                    ("none", "No Formal Education"),
                    ("primary", "Primary School"),
                    ("middle", "Middle School"),
                    ("high_school", "High School Diploma or GED"),
                    ("associate", "Associate Degree"),
                    ("vocational", "Vocational/Technical Certificate"),
                    ("bachelor", "Bachelor's Degree"),
                    ("post_bachelor", "Post-Bachelor Certificate"),
                    ("master", "Master's Degree"),
                    ("post_master", "Post-Master Certificate"),
                    ("doctoral", "Doctoral Degree"),
                    ("professional", "Professional Degree (MD, JD, etc.)"),
                    ("other", "Other"),
                ],
                max_length=30,
                verbose_name="Education Level",
            ),
        ),
        migrations.AlterField(
            model_name="references",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="references",
                to="applicant.applicant",
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="applicant.applicant",
                verbose_name="Applicant",
            ),
        ),
    ]
