# Generated by Django 5.2.3 on 2025-06-20 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applicant_details", "0013_alter_additionalcontext_applicant_reltn_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="awards",
            options={"ordering": ["order"], "verbose_name_plural": "Awards"},
        ),
        migrations.AlterModelOptions(
            name="certification",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="education",
            options={"ordering": ["order"], "verbose_name_plural": "Education"},
        ),
        migrations.AlterModelOptions(
            name="references",
            options={"ordering": ["order"], "verbose_name_plural": "References"},
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["order"]},
        ),
    ]
