# Generated by Django 5.2.3 on 2025-06-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applicant_details",
            "0015_alter_additionalcontext_active_alter_awards_order_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="skill_logo",
            field=models.URLField(
                default="https:www.yourmonm.com", verbose_name="Logo"
            ),
            preserve_default=False,
        ),
    ]
