# Generated by Django 5.2.3 on 2025-06-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant_details", "0016_alter_skill_skill_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="skill_logo",
            field=models.URLField(blank=True, null=True, verbose_name="Logo"),
        ),
    ]
