# Generated by Django 5.2.3 on 2025-06-22 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applicant", "0003_applicant_allow_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PageOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diplay_connect_widget", models.BooleanField(default=True)),
                ("display_download_pdf", models.BooleanField(default=True)),
                (
                    "advanced_config",
                    models.JSONField(
                        blank=True,
                        help_text="Optional: JSON to override or extend base config.",
                        null=True,
                    ),
                ),
                (
                    "applicant_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widget_options",
                        to="applicant.applicant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WidgetOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "advanced_config",
                    models.JSONField(
                        blank=True,
                        help_text="Optional: JSON to override or extend base config.",
                        null=True,
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widget_options",
                        to="site_config.widget",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PageWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("left", "Left Column"),
                            ("right", "Right Column"),
                            ("top", "Top Section"),
                            ("bottom", "Bottom Section"),
                            ("footer", "Footer"),
                        ],
                        default="right",
                        max_length=20,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "advanced_config",
                    models.JSONField(
                        blank=True,
                        help_text="Optional: JSON to override or extend base config.",
                        null=True,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="site_config.page",
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_config.widget",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
                "unique_together": {("page", "widget")},
            },
        ),
    ]
