# Generated by Django 5.2.3 on 2025-06-22 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0003_applicant_allow_feedback"),
        ("site_config", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageoption",
            name="page",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="site_config.page",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pageoption",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page_options",
                to="applicant.applicant",
            ),
        ),
    ]
