# Generated by Django 5.2.3 on 2025-06-22 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0003_applicant_allow_feedback"),
        ("site_config", "0002_pageoption_page_alter_pageoption_applicant_reltn"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagewidget",
            options={},
        ),
        migrations.RenameField(
            model_name="pageoption",
            old_name="diplay_connect_widget",
            new_name="display_connect_widget",
        ),
        migrations.AlterUniqueTogether(
            name="pageoption",
            unique_together={("applicant_reltn", "page")},
        ),
        migrations.RemoveField(
            model_name="pagewidget",
            name="advanced_config",
        ),
        migrations.RemoveField(
            model_name="pagewidget",
            name="display_order",
        ),
        migrations.RemoveField(
            model_name="pagewidget",
            name="is_visible",
        ),
        migrations.AddField(
            model_name="page",
            name="advanced_config",
            field=models.JSONField(
                blank=True,
                help_text="Optional: JSON to override or extend base config.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="widget",
            name="advanced_config",
            field=models.JSONField(
                blank=True,
                help_text="Optional: JSON to override or extend base config.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pagewidget",
            name="location",
            field=models.CharField(
                choices=[
                    ("left", "Left Column"),
                    ("right", "Right Column"),
                    ("footer", "Footer"),
                ],
                default="right",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ApplicantWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widget_orders",
                        to="applicant.applicant",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_config.page",
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_config.widget",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
                "unique_together": {("applicant", "page", "widget")},
            },
        ),
        migrations.CreateModel(
            name="WidgetInstanceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_override",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("other_config", models.JSONField(blank=True, null=True)),
                (
                    "applicant_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widget_instance_options",
                        to="applicant.applicant",
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_config.widget",
                    ),
                ),
            ],
            options={
                "unique_together": {("applicant_reltn", "widget")},
            },
        ),
        migrations.DeleteModel(
            name="WidgetOptions",
        ),
        migrations.RemoveField(
            model_name="pageoption",
            name="advanced_config",
        ),
    ]
