# Generated by Django 5.2.3 on 2025-06-13 22:43

import common.pk_generator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applicant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkHistory",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.pk_generator.generate_id,
                        editable=False,
                        max_length=37,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("employer_name", models.CharField(max_length=100)),
                ("from_date", models.DateField()),
                ("to_field", models.DateField(blank=True, null=True)),
                ("current_employer", models.BooleanField(default=False)),
                (
                    "applicant_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applicant.applicant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkHistoryDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_detail_text", models.CharField(max_length=255)),
                (
                    "work_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="work_details.workhistory",
                    ),
                ),
            ],
        ),
    ]
