# Generated by Django 5.2.3 on 2025-06-21 23:41

import common.pk_generator
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applicant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkHistory",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.pk_generator.generate_id,
                        editable=False,
                        max_length=37,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "employer_name",
                    models.CharField(max_length=100, verbose_name="Employer Name"),
                ),
                (
                    "job_title",
                    models.CharField(max_length=50, verbose_name="Job Title"),
                ),
                ("from_date", models.DateField(verbose_name="Start Date")),
                (
                    "to_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "current_employer",
                    models.BooleanField(default=False, verbose_name="Current Employer"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "applicant_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work",
                        to="applicant.applicant",
                        verbose_name="Applicant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Employer",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WorkHistoryDetails",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=common.pk_generator.generate_id,
                        editable=False,
                        max_length=37,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "work_detail_text",
                    models.CharField(
                        help_text="These are your work bullet points on a resume.",
                        max_length=255,
                        verbose_name="Description",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "work_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_details",
                        to="work_details.workhistory",
                        verbose_name="Employer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Employment Details",
                "ordering": ["order"],
            },
        ),
    ]
