# Generated by Django 5.2.3 on 2025-06-13 23:47

import common.pk_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_details", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workhistorydetails",
            name="id",
            field=models.CharField(
                default=common.pk_generator.generate_id,
                editable=False,
                max_length=37,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
