# Generated by Django 5.2.3 on 2025-06-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_details", "0002_alter_workhistorydetails_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="workhistory",
            name="job_title",
            field=models.CharField(default="poop", max_length=50),
            preserve_default=False,
        ),
    ]
