# Generated by Django 5.2.3 on 2025-06-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_details", "0003_workhistory_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="workhistory",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workhistory",
            name="order",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="workhistorydetails",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workhistorydetails",
            name="order",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
