# Generated by Django 5.2.3 on 2025-06-15 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_details", "0004_workhistory_active_workhistory_order_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workhistory",
            old_name="to_field",
            new_name="to_date",
        ),
    ]
