# Generated by Django 5.2.3 on 2025-06-17 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_details", "0005_rename_to_field_workhistory_to_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workhistorydetails",
            name="work_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_details",
                to="work_details.workhistory",
            ),
        ),
    ]
