# Generated by Django 5.2.3 on 2025-06-19 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0009_alter_applicant_applicant_photo_and_more"),
        ("work_details", "0006_alter_workhistorydetails_work_reltn"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workhistory",
            options={"verbose_name_plural": "Employer"},
        ),
        migrations.AlterField(
            model_name="workhistory",
            name="applicant_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="applicant.applicant",
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="workhistory",
            name="current_employer",
            field=models.BooleanField(default=False, verbose_name="Current Employer"),
        ),
        migrations.AlterField(
            model_name="workhistory",
            name="employer_name",
            field=models.CharField(max_length=100, verbose_name="Employer Name"),
        ),
        migrations.AlterField(
            model_name="workhistory",
            name="from_date",
            field=models.DateField(verbose_name="Start Date"),
        ),
        migrations.AlterField(
            model_name="workhistory",
            name="job_title",
            field=models.CharField(max_length=50, verbose_name="Job Title"),
        ),
        migrations.AlterField(
            model_name="workhistory",
            name="to_date",
            field=models.DateField(blank=True, null=True, verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="workhistorydetails",
            name="work_detail_text",
            field=models.CharField(
                help_text="These are your work bullet points on a resume.",
                max_length=255,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="workhistorydetails",
            name="work_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_details",
                to="work_details.workhistory",
                verbose_name="Employer",
            ),
        ),
    ]
