# Generated by Django 5.2.3 on 2025-06-19 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_details", "0007_alter_workhistory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workhistorydetails",
            options={"verbose_name_plural": "Employment Details"},
        ),
    ]
