# Generated by Django 5.2.3 on 2025-06-20 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_details", "0009_alter_workhistory_applicant_reltn"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workhistory",
            options={"ordering": ["order"], "verbose_name_plural": "Employer"},
        ),
        migrations.AlterModelOptions(
            name="workhistorydetails",
            options={
                "ordering": ["order"],
                "verbose_name_plural": "Employment Details",
            },
        ),
        migrations.RemoveField(
            model_name="workhistory",
            name="active",
        ),
    ]
